/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "FolderTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "MyCDN": {
      "type": "sst.aws.Router"
      "url": string
    }
    "MyConnectionTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MySiteGlobalTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MySocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "MyUGCBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "SENDGRID_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UsersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
